ALTER TABLE phone_numbers ADD COLUMN IF NOT EXISTS verified_name VARCHAR(200) NOT NULL DEFAULT '';
ALTER TABLE phone_numbers ADD COLUMN IF NOT EXISTS about TEXT NOT NULL DEFAULT '';
ALTER TABLE phone_numbers ADD COLUMN IF NOT EXISTS address TEXT NOT NULL DEFAULT '';
ALTER TABLE phone_numbers ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '';
ALTER TABLE phone_numbers ADD COLUMN IF NOT EXISTS email VARCHAR(200) NOT NULL DEFAULT '';
ALTER TABLE phone_numbers ADD COLUMN IF NOT EXISTS websites TEXT NOT NULL DEFAULT '[]';
ALTER TABLE phone_numbers ADD COLUMN IF NOT EXISTS vertical VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE phone_numbers ADD COLUMN IF NOT EXISTS profile_picture_url TEXT NOT NULL DEFAULT '';
ALTER TABLE phone_numbers ADD COLUMN IF NOT EXISTS profile_synced_at TIMESTAMP WITH TIME ZONE;
